# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luolei/code/crawler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luolei/code/crawler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luolei/code/crawler/CMakeFiles /home/luolei/code/crawler/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luolei/code/crawler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named crawler

# Build rule for target.
crawler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crawler
.PHONY : crawler

# fast build rule for target.
crawler/fast:
	$(MAKE) -f CMakeFiles/crawler.dir/build.make CMakeFiles/crawler.dir/build
.PHONY : crawler/fast

#=============================================================================
# Target rules for targets named ContentSeen

# Build rule for target.
ContentSeen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContentSeen
.PHONY : ContentSeen

# fast build rule for target.
ContentSeen/fast:
	$(MAKE) -f component/ContentSeen/CMakeFiles/ContentSeen.dir/build.make component/ContentSeen/CMakeFiles/ContentSeen.dir/build
.PHONY : ContentSeen/fast

#=============================================================================
# Target rules for targets named LinkExtractor

# Build rule for target.
LinkExtractor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LinkExtractor
.PHONY : LinkExtractor

# fast build rule for target.
LinkExtractor/fast:
	$(MAKE) -f component/LinkExtractor/CMakeFiles/LinkExtractor.dir/build.make component/LinkExtractor/CMakeFiles/LinkExtractor.dir/build
.PHONY : LinkExtractor/fast

#=============================================================================
# Target rules for targets named ris

# Build rule for target.
ris: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ris
.PHONY : ris

# fast build rule for target.
ris/fast:
	$(MAKE) -f component/ris/CMakeFiles/ris.dir/build.make component/ris/CMakeFiles/ris.dir/build
.PHONY : ris/fast

#=============================================================================
# Target rules for targets named URLFrontier

# Build rule for target.
URLFrontier: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 URLFrontier
.PHONY : URLFrontier

# fast build rule for target.
URLFrontier/fast:
	$(MAKE) -f component/URLFrontier/CMakeFiles/URLFrontier.dir/build.make component/URLFrontier/CMakeFiles/URLFrontier.dir/build
.PHONY : URLFrontier/fast

#=============================================================================
# Target rules for targets named Writer

# Build rule for target.
Writer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Writer
.PHONY : Writer

# fast build rule for target.
Writer/fast:
	$(MAKE) -f component/Writer/CMakeFiles/Writer.dir/build.make component/Writer/CMakeFiles/Writer.dir/build
.PHONY : Writer/fast

#=============================================================================
# Target rules for targets named TinyDNSResolver

# Build rule for target.
TinyDNSResolver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TinyDNSResolver
.PHONY : TinyDNSResolver

# fast build rule for target.
TinyDNSResolver/fast:
	$(MAKE) -f component/DNS_Resolver/CMakeFiles/TinyDNSResolver.dir/build.make component/DNS_Resolver/CMakeFiles/TinyDNSResolver.dir/build
.PHONY : TinyDNSResolver/fast

#=============================================================================
# Target rules for targets named HttpModule

# Build rule for target.
HttpModule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HttpModule
.PHONY : HttpModule

# fast build rule for target.
HttpModule/fast:
	$(MAKE) -f component/protocolModule/CMakeFiles/HttpModule.dir/build.make component/protocolModule/CMakeFiles/HttpModule.dir/build
.PHONY : HttpModule/fast

#=============================================================================
# Target rules for targets named URLFilter

# Build rule for target.
URLFilter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 URLFilter
.PHONY : URLFilter

# fast build rule for target.
URLFilter/fast:
	$(MAKE) -f component/URLFilter/CMakeFiles/URLFilter.dir/build.make component/URLFilter/CMakeFiles/URLFilter.dir/build
.PHONY : URLFilter/fast

#=============================================================================
# Target rules for targets named URLSeen

# Build rule for target.
URLSeen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 URLSeen
.PHONY : URLSeen

# fast build rule for target.
URLSeen/fast:
	$(MAKE) -f component/URLSeen/CMakeFiles/URLSeen.dir/build.make component/URLSeen/CMakeFiles/URLSeen.dir/build
.PHONY : URLSeen/fast

#=============================================================================
# Target rules for targets named BTTableClass

# Build rule for target.
BTTableClass: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BTTableClass
.PHONY : BTTableClass

# fast build rule for target.
BTTableClass/fast:
	$(MAKE) -f util/btree-f/CMakeFiles/BTTableClass.dir/build.make util/btree-f/CMakeFiles/BTTableClass.dir/build
.PHONY : BTTableClass/fast

#=============================================================================
# Target rules for targets named env

# Build rule for target.
env: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 env
.PHONY : env

# fast build rule for target.
env/fast:
	$(MAKE) -f util/btree-m/CMakeFiles/env.dir/build.make util/btree-m/CMakeFiles/env.dir/build
.PHONY : env/fast

#=============================================================================
# Target rules for targets named Basic_LRU

# Build rule for target.
Basic_LRU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Basic_LRU
.PHONY : Basic_LRU

# fast build rule for target.
Basic_LRU/fast:
	$(MAKE) -f util/lru/CMakeFiles/Basic_LRU.dir/build.make util/lru/CMakeFiles/Basic_LRU.dir/build
.PHONY : Basic_LRU/fast

#=============================================================================
# Target rules for targets named RabinHashFunction64

# Build rule for target.
RabinHashFunction64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RabinHashFunction64
.PHONY : RabinHashFunction64

# fast build rule for target.
RabinHashFunction64/fast:
	$(MAKE) -f util/RabinHash/CMakeFiles/RabinHashFunction64.dir/build.make util/RabinHash/CMakeFiles/RabinHashFunction64.dir/build
.PHONY : RabinHashFunction64/fast

#=============================================================================
# Target rules for targets named rio

# Build rule for target.
rio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rio
.PHONY : rio

# fast build rule for target.
rio/fast:
	$(MAKE) -f util/rio/CMakeFiles/rio.dir/build.make util/rio/CMakeFiles/rio.dir/build
.PHONY : rio/fast

#=============================================================================
# Target rules for targets named Thread_print

# Build rule for target.
Thread_print: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Thread_print
.PHONY : Thread_print

# fast build rule for target.
Thread_print/fast:
	$(MAKE) -f util/thread_print/CMakeFiles/Thread_print.dir/build.make util/thread_print/CMakeFiles/Thread_print.dir/build
.PHONY : Thread_print/fast

clean.o: clean.cpp.o
.PHONY : clean.o

# target to build an object file
clean.cpp.o:
	$(MAKE) -f CMakeFiles/crawler.dir/build.make CMakeFiles/crawler.dir/clean.cpp.o
.PHONY : clean.cpp.o

clean.i: clean.cpp.i
.PHONY : clean.i

# target to preprocess a source file
clean.cpp.i:
	$(MAKE) -f CMakeFiles/crawler.dir/build.make CMakeFiles/crawler.dir/clean.cpp.i
.PHONY : clean.cpp.i

clean.s: clean.cpp.s
.PHONY : clean.s

# target to generate assembly for a file
clean.cpp.s:
	$(MAKE) -f CMakeFiles/crawler.dir/build.make CMakeFiles/crawler.dir/clean.cpp.s
.PHONY : clean.cpp.s

global.o: global.cpp.o
.PHONY : global.o

# target to build an object file
global.cpp.o:
	$(MAKE) -f CMakeFiles/crawler.dir/build.make CMakeFiles/crawler.dir/global.cpp.o
.PHONY : global.cpp.o

global.i: global.cpp.i
.PHONY : global.i

# target to preprocess a source file
global.cpp.i:
	$(MAKE) -f CMakeFiles/crawler.dir/build.make CMakeFiles/crawler.dir/global.cpp.i
.PHONY : global.cpp.i

global.s: global.cpp.s
.PHONY : global.s

# target to generate assembly for a file
global.cpp.s:
	$(MAKE) -f CMakeFiles/crawler.dir/build.make CMakeFiles/crawler.dir/global.cpp.s
.PHONY : global.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/crawler.dir/build.make CMakeFiles/crawler.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/crawler.dir/build.make CMakeFiles/crawler.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/crawler.dir/build.make CMakeFiles/crawler.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... crawler"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ContentSeen"
	@echo "... LinkExtractor"
	@echo "... ris"
	@echo "... URLFrontier"
	@echo "... Writer"
	@echo "... TinyDNSResolver"
	@echo "... HttpModule"
	@echo "... URLFilter"
	@echo "... URLSeen"
	@echo "... BTTableClass"
	@echo "... env"
	@echo "... Basic_LRU"
	@echo "... RabinHashFunction64"
	@echo "... rio"
	@echo "... Thread_print"
	@echo "... clean.o"
	@echo "... clean.i"
	@echo "... clean.s"
	@echo "... global.o"
	@echo "... global.i"
	@echo "... global.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

